title: Your Site Title
description: A simple Jekyll site
baseurl: "" # the subpath of your site, e.g., /blog/
url: "https://lyserg.io"
data-theme: dark

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

permalink: /:title/

#defaults:
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"

#remote_theme: "mmistakes/minimal-mistakes"
remote_theme: "DavideBri/Gesko"

